#!/bin/bash

FLEXISIP=flexisip
SIPP=sipp
NB_USERS=1000
IP=`cat /etc/hosts | grep sip.example.org |  awk -F'\t' '{print $1}'`
PROXY=sip.example.org
REGISTER_PORT=5070
USERS_PORT=5063
INVITER_PORT=5064

# Import configuration
FOLDER=$1
if [ -z $FOLDER ] 
then
 echo "Usage ./launch folder, where folder is "
 ls */launch.config | sed 's/\/.*$//'
 exit
fi
[ ! -f $FOLDER/launch.config ] && echo "config file not found : "$FOLDER/launch.config"" && exit
FLEX_OPTIONS="$FLEX_OPTIONS --configfile $FOLDER/flexisip.conf --port 5060"
. $FOLDER/launch.config

SIPP_COMMONS="$SIPP_COMMONS -i $IP -trace_err"
REG_OPTIONS="$REG_OPTIONS -p 5070 -m `echo "1+$NB_USERS"|bc` $SIPP_COMMONS"
REG_INVITER_OPTIONS="$REG_INVITER_OPTIONS -p 5064 -m 1 $SIPP_COMMONS"
INV_OPTIONS="$INV_OPTIONS -m $NB_USERS -p 5064 $SIPP_COMMONS"
UAS_OPTIONS="$UAS_OPTIONS -p 5063 -bg $SIPP_COMMONS -mi $IP -mp 15000 -rtp_echo"

echo "Using FLEXISIP=$FLEXISIP,SIPP$SIPP,NB_USERS=$NB_USERS"
echo "IP=$IP,PROXY=$PROXY"
echo "Sofia SIP log level: $SU_DEBUG, LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

# Accept core dumps
ulimit -c unlimited

# Open many file descriptors
ulimit -n 65000


echo ""; echo "Start users listening: $SIPP -sf uas.xml $UAS_OPTIONS"
$SIPP -sf uas.xml $UAS_OPTIONS 2>&1 > /dev/null

echo ""; echo "Start flexisip: $FLEXISIP $FLEX_OPTIONS"
$FLEXISIP $FLEX_OPTIONS 2>&1 > flexisip.log &
sleep 2s

echo ""; echo "Register users $SIPP $PROXY -sf register_users.xml $REG_OPTIONS"
$SIPP $PROXY -sf register_users.xml $REG_OPTIONS
echo ""; echo "Register inviter $SIPP $PROXY -sf register_inviter.xml $REG_INVITER_OPTIONS"
$SIPP $PROXY -sf register_inviter.xml $REG_INVITER_OPTIONS



# Allow killing
function onexit() {
 echo "Killing everyone"
 killall flexisip 2>/dev/null
 killall sipp 2>/dev/null

 LOGS=logs/"$FOLDER"_`date '+%s'`
 LOGS_TO_SAVE=$FOLDER"/*.log *.log core"
 mkdir -p $LOGS
 mv $LOGS_TO_SAVE $LOGS

 exit
}
set -o errtrace 
trap onexit 1 2 3 15 ERR

echo "" ; echo "Start inviting users : $INV_OPTIONS"
while [ true ]
do
  $SIPP $PROXY -sf $FOLDER/invite.xml $INV_OPTIONS
done

onexit 
