#!/bin/sh
#
# axtunnel This script starts and stops the axtunnel_server daemon
#
# chkconfig: - 78 30
# processname: flexisip
# description: flexisip SIP proxy
#

# Source function library.
. /etc/rc.d/init.d/functions

prog="flexisip"

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# Set default axtunnel_server configuration.
FLEXISIP_OPTIONS="--daemon --syslog"
FLEXISIP_PID=/var/run/flexisip.pid

[ -f /usr/bin/$prog -o -f /usr/local/bin/$prog ] || exit 0
PATH=$PATH:/usr/bin:/usr/local/bin

# By default it's all good
RETVAL=0

# See how we were called.
case "$1" in
  start)
	# Start daemon.
	echo -n $"Starting $prog: "
	daemon $NICELEVEL $prog $FLEXISIP_OPTIONS --pidfile $FLEXISIP_PID
	RETVAL=$?
        echo
	if [ $RETVAL = 0 ]; then
		touch /var/lock/subsys/flexisip
	fi
        ;;
  stop)
        # Stop daemons.
        echo -n $"Stopping $prog: "
        killproc flexisip
        RETVAL=$?
        echo
	if [ $RETVAL = 0 ]; then
		rm -f /var/lock/subsys/flexisip
		rm -f $FLEXISIP_PID
	fi
        ;;
  restart)
        $0 stop
	sleep 3
        $0 start
        ;;
  condrestart)
       [ -e /var/lock/subsys/flexisip ] && $0 restart
       ;;
  status)
	status flexisip
	RETVAL=$?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status|condrestart}"
	RETVAL=1
	;;
esac

exit $RETVAL
