variables:
  DEBIAN12_CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON

.debian12-image:
  image:
    name: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: ${DEBIAN12_CMAKE_OPTIONS}

#################################################
# Makefile
#################################################

# Disable gcc jobs as gcc is too old for a full c++20 support
#job-debian12-makefile-gcc:
#  extends:
#    - .job-makefile-gcc
#    - .debian12-image
#    - .rules-manual  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-debian12-makefile-clang:
  extends:
    - .job-makefile-clang
    - .debian12-image
    - .rules-manual  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

# Disable gcc jobs as gcc is too old for a full c++20 support
#job-debian12-ninja-gcc:
#  extends:
#    - .job-ninja-gcc
#    - .debian12-image
#    # Debian 12 packages GCC 12 (fitting!) for which our cmake has special-caseing,
#    # so let's override the .job-ninja-gcc rules to run it in dev pipelines
#    - .rules-dev  # ⚠ See `rules.yml`
#  variables:
#    CMAKE_OPTIONS: ${DEBIAN12_CMAKE_OPTIONS}


job-debian12-ninja-clang:
  extends:
    - .job-ninja-clang
    - .debian12-image
    - .rules-dev
    - .tester-artifacts
  variables:
    CMAKE_OPTIONS: ${DEBIAN12_CMAKE_OPTIONS} -DENABLE_UNIT_TESTS=ON

#################################################
# UNIT TESTS
#################################################

job-debian12-unit-test:
  extends:
    - .unit-test
    - .debian12-image
  needs:
    - job-debian12-ninja-clang
  artifacts:
    when: always
    paths:
      - work/lib/libflexisip.so
      - ${LOGS_DIR}/*

#################################################
# DEB
#################################################

job-debian12-deb:
  extends:
    - .job-linux-deb
    - .debian12-image
  needs:
    - job: job-debian12-unit-test
      optional: true
      artifacts: false
    - job: job-debian12-ninja-clang
      optional: true
      artifacts: false
  variables:
    # Only use clang for debian 12 to fully support C++20
    CC: clang
    CXX: clang++

# Test installation of the DEB package, check its feature list and files permissions
job-debian12-deb-check-package:
  stage: check-package 📤
  tags: [ "docker-flat" ]
  image: debian:12
  rules:
    - !reference [job-debian12-deb, rules]
  needs:
    - job: job-debian12-deb
  variables:
    GIT_STRATEGY: none
  script:
    - !reference [.job-deb-check-package, script]

job-debian12-deb-deploy:
  extends:
    - .job-deploy
    - .debian12-image
  variables:
    DISTRIB: debian
    RELEASE: bookworm
  dependencies:
    - job-debian12-deb
