.archlinux-image-variables:
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION

#################################################
# Makefile
#################################################

job-archlinux-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .archlinux-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-archlinux-makefile-clang:
  extends:
    - .job-makefile-clang
    - .archlinux-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

job-archlinux-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .archlinux-image-variables
  rules:
    - !reference [job-archlinux-ninja-clang, rules]


job-archlinux-ninja-clang:
  extends:
    - .job-ninja-clang
    - .archlinux-image-variables
