.ubuntu-18-04-image-variables:
  image:
    name: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON

#################################################
# Makefile
#################################################

job-ubuntu-18-04-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .ubuntu-18-04-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-ubuntu-18-04-makefile-clang:
  extends:
    - .job-makefile-clang
    - .ubuntu-18-04-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

job-ubuntu-18-04-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .ubuntu-18-04-image-variables


job-ubuntu-18-04-ninja-clang:
  extends:
    - .job-ninja-clang
    - .ubuntu-18-04-image-variables
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON -DENABLE_UNIT_TESTS=ON -DENABLE_UNIT_TESTS_MYSQL=ON
  artifacts:
    paths:
      - OUTPUT/*
      - sanitizer_ignore.txt

#################################################
# UNIT TESTS
#################################################

job-ubuntu-18-04-unit-test:
  extends:
    - .unit-test
    - .ubuntu-18-04-image-variables
  needs:
    - job-ubuntu-18-04-ninja-clang

#################################################
# DEB
#################################################

job-ubuntu-18-04-deb:
  extends:
    - .job-linux-deb
    - .ubuntu-18-04-image-variables
    - .rules-manual-deploy # ⚠ See `rules.yml`, override .job-linux-deb rules
  needs:
    - job: job-ubuntu-18-04-unit-test
      optional: true
      artifacts: false
    - job: job-ubuntu-18-04-ninja-clang
      optional: true
      artifacts: false


job-ubuntu-18-04-deb-deploy:
  extends:
    - .job-debian-deb-deploy
    - .ubuntu-18-04-image-variables
  variables:
    RELEASE: bionic
    FREIGHT_PATH: $UBUNTU_FREIGHT_CONF_PATH
  dependencies:
    - job-ubuntu-18-04-deb
