/*
    Flexisip, a flexible SIP proxy server with media capabilities.
    Copyright (C) 2010-2015  Belledonne Communications SARL, All rights reserved.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
 * Note: this file originally auto-generated by mib2c using
 *        mib2c.flexisip.conf 
 */
#ifndef FLEXISIPMIB_H
#define FLEXISIPMIB_H
class ConfigManager;
class Agent;
/* function declarations */
void init_flexisipMIB(Agent& agent,ConfigManager& cm);
Netsnmp_Node_Handler handle_autoRespawn;
Netsnmp_Node_Handler handle_aliases;
Netsnmp_Node_Handler handle_ipAddress;
Netsnmp_Node_Handler handle_bindAddress;
Netsnmp_Node_Handler handle_port;
Netsnmp_Node_Handler handle_transportUris;
Netsnmp_Node_Handler handle_totalNumberOfAddedRecords;
Netsnmp_Node_Handler handle_totalNumberOfExpiredRecords;

#endif /* FLEXISIPMIB_H */
