name: Documentation
description: Ask for additions and/or clarifications in the official documentation.
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
        
        ### Disclaimer
        Responses are provided by the community and, on a best effort basis, by some Belledonne Communications SARL engineers working on Flexisip and its related projects.
        The community means any people all around the world simply willing to participate to the discussions.
        
        Belledonne Communications SARL disclaims any WARRANTY that the content posted on Github issues or mailing lists is technically correct.
        Responses from Belledonne Communications SARL engineers shall be considered as individual contributions and shall not be seen as Belledonne Communications official point of view or commitment.
        
        ### Reminder
        Software engineers at Belledonne Communications will mainly process the following issues:
          - detailed bug reports
          - documentation requests (additions and/or clarifications)
          - any questions regarding SIP, Flexisip and its software architecture
        
        People using Flexisip or its related projects within the scope of their company job are invited to contact [Belledonne Communications](https://www.linphone.org/en/contact/) in order to obtain commercial support.
  - type: textarea
    id: request
    attributes:
      label: Documentation request
      description: A clear and concise description of what need clarifications regarding the Flexisip documentation.
    validations:
      required: true