#!/bin/bash
ulimit -c unlimited*
set -- flexisip "$@"

_term() {
  pkill $child
}
_termAll() {
  for pid in $(ps -ef | awk '/flexisip --debug/ {print $2}'); do
    kill -SIGTERM $pid
    wait $pid
  done
}

# Wait for needed container startup
/wait || exit $?

echo "Flexisip docker params : $*"

ASAN_OPTIONS="atexit=true"
export ASAN_OPTIONS

if [[ $@ == *"--server"* ]]; then
   trap _term SIGTERM
  echo "--server param found, starting only one Flexisip instance"
  "$@" &
  child=$!
else
  trap _termAll SIGTERM
  echo "Server param not found, starting 3 Flexisip instances (proxy, presence, conference)"
  ( "$@" --server proxy 2>&1| tee /var/opt/belledonne-communications/log/flexisip/flexisip_proxy_stdout.log ) &
  ( "$@" --server presence 2>&1| tee /var/opt/belledonne-communications/log/flexisip/flexisip_presence_stdout.log ) &
  ( "$@" --server conference 2>&1| tee /var/opt/belledonne-communications/log/flexisip/flexisip_conference_stdout.log ) &
fi

wait -n

echo "At least one server crashed, stopping every sub process that is still alive"
pkill -P $$

# Core dump management, used in unit tests
# we execute gdb on each core dump, with the options given in backtrace.gdb file
# we search in /root because it's the workdir set in Dockerfile and because by default our core dumps are generated by default in the working directory
if [ -n "$(find /root -type f -name "core*")" ]; then
	find /root -type f -name "core*" | xargs -L1 gdb flexisip -x /backtrace.gdb;
fi