// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef XML_COMMON_SCHEMA_HH
#define XML_COMMON_SCHEMA_HH

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
#if __clang__ || __GNUC__ >= 4
	#pragma GCC diagnostic push
	#pragma GCC diagnostic ignored "-Wfloat-equal"
	#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
#ifndef __ANDROID__
	#pragma GCC diagnostic ignored "-Wsuggest-override"
#endif
#endif
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

#include <xsd/cxx/tree/std-ostream-operators.hxx>

namespace Xsd
{
  namespace XmlSchema
  {
    // anyType and anySimpleType.
    //
    typedef ::xsd::cxx::tree::type Type;
    typedef ::xsd::cxx::tree::simple_type< char, Type > SimpleType;
    typedef ::xsd::cxx::tree::type Container;

    // 8-bit
    //
    typedef signed char Byte;
    typedef unsigned char UnsignedByte;

    // 16-bit
    //
    typedef short Short;
    typedef unsigned short UnsignedShort;

    // 32-bit
    //
    typedef int Int;
    typedef unsigned int UnsignedInt;

    // 64-bit
    //
    typedef long long Long;
    typedef unsigned long long UnsignedLong;

    // Supposed to be arbitrary-length integral types.
    //
    typedef long long Integer;
    typedef long long NonPositiveInteger;
    typedef unsigned long long NonNegativeInteger;
    typedef unsigned long long PositiveInteger;
    typedef long long NegativeInteger;

    // Boolean.
    //
    typedef bool Boolean;

    // Floating-point types.
    //
    typedef float Float;
    typedef double Double;
    typedef double Decimal;

    // String types.
    //
    typedef ::xsd::cxx::tree::string< char, SimpleType > String;
    typedef ::xsd::cxx::tree::normalized_string< char, String > NormalizedString;
    typedef ::xsd::cxx::tree::token< char, NormalizedString > Token;
    typedef ::xsd::cxx::tree::name< char, Token > Name;
    typedef ::xsd::cxx::tree::nmtoken< char, Token > Nmtoken;
    typedef ::xsd::cxx::tree::nmtokens< char, SimpleType, Nmtoken > Nmtokens;
    typedef ::xsd::cxx::tree::ncname< char, Name > Ncname;
    typedef ::xsd::cxx::tree::language< char, Token > Language;

    // ID/IDREF.
    //
    typedef ::xsd::cxx::tree::id< char, Ncname > Id;
    typedef ::xsd::cxx::tree::idref< char, Ncname, Type > Idref;
    typedef ::xsd::cxx::tree::idrefs< char, SimpleType, Idref > Idrefs;

    // URI.
    //
    typedef ::xsd::cxx::tree::uri< char, SimpleType > Uri;

    // Qualified name.
    //
    typedef ::xsd::cxx::tree::qname< char, SimpleType, Uri, Ncname > Qname;

    // Binary.
    //
    typedef ::xsd::cxx::tree::buffer< char > Buffer;
    typedef ::xsd::cxx::tree::base64_binary< char, SimpleType > Base64Binary;
    typedef ::xsd::cxx::tree::hex_binary< char, SimpleType > HexBinary;

    // Date/time.
    //
    typedef ::xsd::cxx::tree::time_zone TimeZone;
    typedef ::xsd::cxx::tree::date< char, SimpleType > Date;
    typedef ::xsd::cxx::tree::date_time< char, SimpleType > DateTime;
    typedef ::xsd::cxx::tree::duration< char, SimpleType > Duration;
    typedef ::xsd::cxx::tree::gday< char, SimpleType > Gday;
    typedef ::xsd::cxx::tree::gmonth< char, SimpleType > Gmonth;
    typedef ::xsd::cxx::tree::gmonth_day< char, SimpleType > GmonthDay;
    typedef ::xsd::cxx::tree::gyear< char, SimpleType > Gyear;
    typedef ::xsd::cxx::tree::gyear_month< char, SimpleType > GyearMonth;
    typedef ::xsd::cxx::tree::time< char, SimpleType > Time;

    // Entity.
    //
    typedef ::xsd::cxx::tree::entity< char, Ncname > Entity;
    typedef ::xsd::cxx::tree::entities< char, SimpleType, Entity > Entities;

    typedef ::xsd::cxx::tree::content_order ContentOrder;
    // Namespace information and list stream. Used in
    // serialization functions.
    //
    typedef ::xsd::cxx::xml::dom::namespace_info< char > NamespaceInfo;
    typedef ::xsd::cxx::xml::dom::namespace_infomap< char > NamespaceInfomap;
    typedef ::xsd::cxx::tree::list_stream< char > ListStream;
    typedef ::xsd::cxx::tree::as_double< Double > AsDouble;
    typedef ::xsd::cxx::tree::as_decimal< Decimal > AsDecimal;
    typedef ::xsd::cxx::tree::facet Facet;

    // Flags and properties.
    //
    typedef ::xsd::cxx::tree::flags Flags;
    typedef ::xsd::cxx::tree::properties< char > Properties;

    // Parsing/serialization diagnostics.
    //
    typedef ::xsd::cxx::tree::severity Severity;
    typedef ::xsd::cxx::tree::error< char > Error;
    typedef ::xsd::cxx::tree::diagnostics< char > Diagnostics;

    // Exceptions.
    //
    typedef ::xsd::cxx::tree::exception< char > Exception;
    typedef ::xsd::cxx::tree::bounds< char > Bounds;
    typedef ::xsd::cxx::tree::duplicate_id< char > DuplicateId;
    typedef ::xsd::cxx::tree::parsing< char > Parsing;
    typedef ::xsd::cxx::tree::expected_element< char > ExpectedElement;
    typedef ::xsd::cxx::tree::unexpected_element< char > UnexpectedElement;
    typedef ::xsd::cxx::tree::expected_attribute< char > ExpectedAttribute;
    typedef ::xsd::cxx::tree::unexpected_enumerator< char > UnexpectedEnumerator;
    typedef ::xsd::cxx::tree::expected_text_content< char > ExpectedTextContent;
    typedef ::xsd::cxx::tree::no_prefix_mapping< char > NoPrefixMapping;
    typedef ::xsd::cxx::tree::serialization< char > Serialization;

    // Error handler callback interface.
    //
    typedef ::xsd::cxx::xml::error_handler< char > ErrorHandler;

    // DOM interaction.
    //
    namespace dom
    {
      // Automatic pointer for DOMDocument.
      //
      using ::xsd::cxx::xml::dom::unique_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XSD__XMLSCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XSD__XMLSCHEMA
      // DOM user data key for back pointers to tree nodes.
      //
      const XMLCh* const treeNodeKey = ::xsd::cxx::tree::user_data_keys::node;
#endif
    }
  }
}

// Forward declarations.
//
class Timestamp_t;
class DeviceID_t;
class Note_t;
class Empty;

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include <xsd/cxx/tree/containers-wildcard.hxx>

#include "xml.hh"

class Timestamp_t: public ::Xsd::XmlSchema::DateTime
{
  public:
  // Constructors.
  //
  Timestamp_t (const ::Xsd::XmlSchema::DateTime&);

  Timestamp_t (const ::xercesc::DOMElement& e,
               ::Xsd::XmlSchema::Flags f = 0,
               ::Xsd::XmlSchema::Container* c = 0);

  Timestamp_t (const ::xercesc::DOMAttr& a,
               ::Xsd::XmlSchema::Flags f = 0,
               ::Xsd::XmlSchema::Container* c = 0);

  Timestamp_t (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::Xsd::XmlSchema::Flags f = 0,
               ::Xsd::XmlSchema::Container* c = 0);

  Timestamp_t (const Timestamp_t& x,
               ::Xsd::XmlSchema::Flags f = 0,
               ::Xsd::XmlSchema::Container* c = 0);

  virtual Timestamp_t*
  _clone (::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0) const;

  virtual 
  ~Timestamp_t ();
};

class DeviceID_t: public ::Xsd::XmlSchema::Uri
{
  public:
  // Constructors.
  //
  DeviceID_t (const ::Xsd::XmlSchema::Uri&);

  DeviceID_t (const ::xercesc::DOMElement& e,
              ::Xsd::XmlSchema::Flags f = 0,
              ::Xsd::XmlSchema::Container* c = 0);

  DeviceID_t (const ::xercesc::DOMAttr& a,
              ::Xsd::XmlSchema::Flags f = 0,
              ::Xsd::XmlSchema::Container* c = 0);

  DeviceID_t (const ::std::string& s,
              const ::xercesc::DOMElement* e,
              ::Xsd::XmlSchema::Flags f = 0,
              ::Xsd::XmlSchema::Container* c = 0);

  DeviceID_t (const DeviceID_t& x,
              ::Xsd::XmlSchema::Flags f = 0,
              ::Xsd::XmlSchema::Container* c = 0);

  virtual DeviceID_t*
  _clone (::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0) const;

  virtual 
  ~DeviceID_t ();
};

class Note_t: public ::Xsd::XmlSchema::String
{
  public:
  // lang
  //
  typedef ::namespace_::Lang LangType;
  typedef ::xsd::cxx::tree::optional< LangType > LangOptional;
  typedef ::xsd::cxx::tree::traits< LangType, char > LangTraits;

  const LangOptional&
  getLang () const;

  LangOptional&
  getLang ();

  void
  setLang (const LangType& x);

  void
  setLang (const LangOptional& x);

  void
  setLang (::std::unique_ptr< LangType > p);

  // Constructors.
  //
  Note_t ();

  Note_t (const char*);

  Note_t (const ::std::string&);

  Note_t (const ::Xsd::XmlSchema::String&);

  Note_t (const ::xercesc::DOMElement& e,
          ::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0);

  Note_t (const Note_t& x,
          ::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0);

  virtual Note_t*
  _clone (::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0) const;

  Note_t&
  operator= (const Note_t& x);

  virtual 
  ~Note_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::Xsd::XmlSchema::Flags);

  protected:
  LangOptional lang_;
};

class Empty: public ::Xsd::XmlSchema::Type
{
  public:
  // Constructors.
  //
  Empty ();

  Empty (const ::xercesc::DOMElement& e,
         ::Xsd::XmlSchema::Flags f = 0,
         ::Xsd::XmlSchema::Container* c = 0);

  Empty (const ::xercesc::DOMAttr& a,
         ::Xsd::XmlSchema::Flags f = 0,
         ::Xsd::XmlSchema::Container* c = 0);

  Empty (const ::std::string& s,
         const ::xercesc::DOMElement* e,
         ::Xsd::XmlSchema::Flags f = 0,
         ::Xsd::XmlSchema::Container* c = 0);

  Empty (const Empty& x,
         ::Xsd::XmlSchema::Flags f = 0,
         ::Xsd::XmlSchema::Container* c = 0);

  virtual Empty*
  _clone (::Xsd::XmlSchema::Flags f = 0,
          ::Xsd::XmlSchema::Container* c = 0) const;

  virtual 
  ~Empty ();
};

#include <iosfwd>

::std::ostream&
operator<< (::std::ostream&, const Timestamp_t&);

::std::ostream&
operator<< (::std::ostream&, const DeviceID_t&);

::std::ostream&
operator<< (::std::ostream&, const Note_t&);

::std::ostream&
operator<< (::std::ostream&, const Empty&);

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

void
operator<< (::xercesc::DOMElement&, const Timestamp_t&);

void
operator<< (::xercesc::DOMAttr&, const Timestamp_t&);

void
operator<< (::Xsd::XmlSchema::ListStream&,
            const Timestamp_t&);

void
operator<< (::xercesc::DOMElement&, const DeviceID_t&);

void
operator<< (::xercesc::DOMAttr&, const DeviceID_t&);

void
operator<< (::Xsd::XmlSchema::ListStream&,
            const DeviceID_t&);

void
operator<< (::xercesc::DOMElement&, const Note_t&);

void
operator<< (::xercesc::DOMElement&, const Empty&);

void
operator<< (::xercesc::DOMAttr&, const Empty&);

void
operator<< (::Xsd::XmlSchema::ListStream&,
            const Empty&);

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
#if __clang__ || __GNUC__ >= 4
	#pragma GCC diagnostic pop
#endif
//
// End epilogue.

#endif // XML_COMMON_SCHEMA_HH
