// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#ifndef XML_SIMPL_HXX
#define XML_SIMPL_HXX

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#ifndef XSDE_OMIT_SAGGR
#  define XSDE_OMIT_SAGGR
#  define XML_SIMPL_HXX_CLEAR_OMIT_SAGGR
#endif

#include "xml-sskel.hxx"

#include <xsde/cxx/stack.hxx>

namespace namespace_
{
  class lang_simpl: public lang_sskel
  {
    public:
    virtual void
    pre (const ::namespace_::lang&);

    virtual void
    _serialize_content ();

    public:
    const ::namespace_::lang* lang_simpl_state_;
  };

  class space_simpl: public space_sskel
  {
    public:
    space_simpl ();

    virtual void
    pre (const ::namespace_::space&);

    virtual void
    _serialize_content ();

    public:
    const ::namespace_::space* space_simpl_state_;
  };

  class lang_member_simpl: public lang_member_sskel
  {
    public:
    lang_member_simpl ();

    virtual void
    pre (const ::namespace_::lang_member&);

    virtual void
    _serialize_content ();

    public:
    const ::namespace_::lang_member* lang_member_simpl_state_;
  };
}

#ifdef XML_SIMPL_HXX_CLEAR_OMIT_SAGGR
#  undef XSDE_OMIT_SAGGR
#endif

#ifndef XSDE_OMIT_SAGGR

#endif // XSDE_OMIT_SAGGR

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // XML_SIMPL_HXX
